#!/usr/bin/env python3
"""
Auto-generated script to run α,β-CROWN verification.
Generated by verify_with_abcrown.py
"""

import sys
import os
from pathlib import Path

# Add α,β-CROWN to path (adjust if needed)
abcrown_path = Path(os.environ.get('ALPHABETACROWN_PATH', '../alpha-beta-CROWN'))
if not abcrown_path.exists():
    abcrown_path = Path.home() / 'alpha-beta-CROWN'
if not abcrown_path.exists():
    print("ERROR: α,β-CROWN not found. Please set ALPHABETACROWN_PATH or install it.")
    sys.exit(1)

sys.path.insert(0, str(abcrown_path / 'complete_verifier'))

try:
    from auto_LiRPA import BoundedModule, BoundedTensor
    from auto_LiRPA.perturbations import PerturbationLpNorm
    from bab import verify_property
    import torch
    import onnx
    import numpy as np
except ImportError as e:
    print(f"ERROR: Missing dependency: {e}")
    print("Please ensure you're in the alpha-beta-crown conda environment")
    sys.exit(1)

# Load configuration
import yaml
with open('verification/abcrown_config.yaml', 'r') as f:
    config = yaml.safe_load(f)

# Load ONNX model
onnx_path = config['model']['onnx_path']
print(f"Loading ONNX model from: {onnx_path}")

# Convert ONNX to PyTorch
# Note: This is a simplified version. You may need to adjust based on your ONNX model structure.
try:
    import onnxruntime as ort
    session = ort.InferenceSession(onnx_path)
    input_name = session.get_inputs()[0].name
    input_shape = session.get_inputs()[0].shape
    print(f"Model input: {input_name}, shape: {input_shape}")
except Exception as e:
    print(f"ERROR loading ONNX: {e}")
    sys.exit(1)

# Get input bounds
input_bounds = config['specification']['input_bounds']
print(f"Input bounds: {input_bounds}")

# Create verification property
# For monotonicity: verify that output is non-increasing in cycle
monotone_var = config['specification']['monotonicity_constraints']['variable']
direction = config['specification']['monotonicity_constraints']['direction']

print(f"Verifying monotonicity: variable {monotone_var}, direction {direction}")
print("(direction -1 means decreasing: cycle ↑ → RUL ↓)")

# Run verification
# Note: This is a template. Actual α,β-CROWN API may vary.
# You may need to use the abcrown.py command-line tool instead:
print("\nTo run verification, use:")
print(f"  cd {abcrown_path}")
print(f"  python abcrown.py --config /gpfs/radev/scratch/xu_hua/mj756/course_proj/NNV/verification/abcrown_config.yaml")
